SzyfyBezpieczenstwoSysKomp/Controllers/CezarController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using SzyfyBezpieczenstwoSysKomp.Models;

namespace SzyfyBezpieczenstwoSysKomp.Controllers
{
    public class CezarController : Controller
    {
        private readonly ILogger<CezarController> _logger;

        public CezarController(ILogger<CezarController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View("~/Views/SzyfrCezara/Cezar.cshtml", new CezarModel());
        }

        [HttpPost]
        public IActionResult Index(CezarModel model, string operacja)
        {
            _logger.LogInformation(
                "Operacja: {Operacja}, Tekst przed szyfrowaniem: {Tekst}, Przesunięcie: {Przesuniecie}",
                operacja, model.TekstPrzedSzyfrowaniem, model.Przesuniecie);
            if (string.IsNullOrEmpty(model.TekstPrzedSzyfrowaniem))
            {
                ModelState.AddModelError("TekstPrzedSzyfrowaniem", "Tekst do szyfrowania nie może być pusty.");
            }
            if (model.Przesuniecie == 0)
            {
                ModelState.AddModelError("Przesuniecie", "Przesunięcie nie może wynosić 0.");
            }
            if (ModelState.IsValid)
            {
                int przesuniecie = operacja == "Odszyfrowanie" ? -model.Przesuniecie : model.Przesuniecie;
                model.TekstZaszyfrowany = Szyfrowanie(model.TekstPrzedSzyfrowaniem, przesuniecie);
            }

            return View("~/Views/SzyfrCezara/Cezar.cshtml", model);
        }

        private string Szyfrowanie(string tekst, int przesuniecie)
        {
            string maleLitery = "aąbcćdeęfghijklłmnńoópqrsśtuvwxyzźż";
            string duzeLitery = "AĄBCĆDEĘFGHIJKLŁMNŃOÓPQRSŚTUVWXYZŹŻ";

            char[] znaki = tekst.ToCharArray();
            for (int i = 0; i < znaki.Length; i++)
            {
                char znak = znaki[i];
                if (char.IsLetter(znak))
                {
                    if (maleLitery.Contains(znak))
                    {
                        int indeks = (maleLitery.IndexOf(znak) + przesuniecie) % maleLitery.Length;
                        if (indeks < 0) indeks += maleLitery.Length;
                        znaki[i] = maleLitery[indeks];
                    }
                    else if (duzeLitery.Contains(znak))
                    {
                        int indeks = (duzeLitery.IndexOf(znak) + przesuniecie) % duzeLitery.Length;
                        if (indeks < 0) indeks += duzeLitery.Length;
                        znaki[i] = duzeLitery[indeks];
                    }
                }
            }

            return new string(znaki);
        }
    }
}

SzyfyBezpieczenstwoSysKomp/Controllers/PolibiuszController.cs
using System.Numerics;
using Microsoft.AspNetCore.Mvc;
using SzyfyBezpieczenstwoSysKomp.Models;
using SzyfyBezpieczenstwoSysKomp.Models.Polibiusz;

namespace SzyfyBezpieczenstwoSysKomp.Controllers
{
    public class PolibiuszController : Controller
    {
        private readonly PolibiuszModel _polibiuszModel;

        public PolibiuszController()
        {
            _polibiuszModel = new PolibiuszModel();
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View("~/Views/Polibiusz/Index.cshtml");
        }
        
        [HttpPost]
        public IActionResult Encrypt(string inputText)
        {
            var grid = _polibiuszModel.GenerateRandomGrid();
            var encrypted = _polibiuszModel.EncryptWithPolibius(inputText, grid);

            string encryptedNumberString = encrypted.Replace(" ", ""); 
            BigInteger x = BigInteger.Parse(encryptedNumberString); 

            Random random = new Random();
            int a = random.Next(1, 11); 
            int b = random.Next(1, 11); 
            BigInteger y = (a * x * x )+ b; 

            var model = new PolibiuszResultModel
            {
                Grid = grid,
                EncryptedText = encrypted,
                Result = y
            };

            return View("~/Views/Polibiusz/Index.cshtml", model);
        }
        
        public static BigInteger Sqrt(BigInteger value)
        {
            if (value < 0)
                throw new ArgumentException("Nie można obliczyć pierwiastka kwadratowego z liczby ujemnej.");

            if (value == 0)
                return 0;

            BigInteger n = (value / 2) + 1;
            BigInteger n1 = (n + (value / n)) / 2;

            while (n1 < n)
            {
                n = n1;
                n1 = (n + (value / n)) / 2;
            }

            return n;
            
        }
    }
}

SzyfyBezpieczenstwoSysKomp/Controllers/VigenereController.cs
using Microsoft.AspNetCore.Mvc;

namespace SzyfyBezpieczenstwoSysKomp.Controllers
{
    public class VigenereController : Controller
    {
        private static readonly char[] PolishAlphabet = 
        {
            'a', 'ą', 'b', 'c', 'ć', 'd', 'e', 'ę', 'f', 'g', 'h', 'i', 'j', 'k', 
            'l', 'ł', 'm', 'n', 'ń', 'o', 'ó', 'p', 'q', 'r', 's', 'ś', 't', 'u', 
            'v', 'w', 'x', 'y', 'z', 'ź', 'ż'
        };

        public IActionResult Index()
        {
            return View("~/Views/SzyfrVigenere/Vigenere.cshtml");
        }

        [HttpPost]
        public IActionResult Index(string message, string key, bool isEncrypting)
        {
            if (!string.IsNullOrEmpty(message) && !string.IsNullOrEmpty(key))
            {
                ViewBag.Result = isEncrypting
                    ? Encrypt(message, key)
                    : Decrypt(message, key);
            }
            else
            {
                ViewBag.Result = "Wprowadź poprawne dane!";
            }
            return View("~/Views/SzyfrVigenere/Vigenere.cshtml");
        }

        private string Encrypt(string text, string key)
        {
            string result = "";
            key = RepeatKey(key, text.Length).ToLower(); 

            for (int i = 0; i < text.Length; i++)
            {
                char currentChar = char.ToLower(text[i]);
                int charIndex = Array.IndexOf(PolishAlphabet, currentChar);

                if (charIndex != -1) 
                {
                    int keyIndex = Array.IndexOf(PolishAlphabet, key[i]);
                    int newIndex = (charIndex + keyIndex) % 35;

                    char newChar = PolishAlphabet[newIndex];
                    result += char.IsUpper(text[i]) ? char.ToUpper(newChar) : newChar;
                }
                else
                {
                    result += text[i]; 
                }
            }

            return result;
        }

        private string Decrypt(string text, string key)
        {
            string result = "";
            key = RepeatKey(key, text.Length).ToLower(); 

            for (int i = 0; i < text.Length; i++)
            {
                char currentChar = char.ToLower(text[i]);
                int charIndex = Array.IndexOf(PolishAlphabet, currentChar);

                if (charIndex != -1) 
                {
                    int keyIndex = Array.IndexOf(PolishAlphabet, key[i]);
                    int newIndex = (charIndex - keyIndex + 35) % 35;

                    char newChar = PolishAlphabet[newIndex];
                    result += char.IsUpper(text[i]) ? char.ToUpper(newChar) : newChar;
                }
                else
                {
                    result += text[i]; 
                }
            }

            return result;
        }

        private string RepeatKey(string key, int length)
        {
            var repeatedKey = new List<char>();
            int keyLength = key.Length;

            for (int i = 0; i < length; i++)
            {
                repeatedKey.Add(key[i % keyLength]);
            }

            return new string(repeatedKey.ToArray());
        }
    }
}

SzyfyBezpieczenstwoSysKomp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - SzyfyBezpieczenstwoSysKomp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <link rel="stylesheet" href="~/SzyfyBezpieczenstwoSysKomp.styles.css" asp-append-version="true"/>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SzyfyBezpieczenstwoSysKomp</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Cezar" asp-action="Index">Szyfr Cezara</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Polibiusz" asp-action="Index">Szyfr Polibiusza</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Vigenere" asp-action="Index">Szyfr Vigenère'a</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
</header>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>

<footer class="border-top footer text-muted">
    <div class="container">
        &copy; 2024 - SzyfyBezpieczenstwoSysKomp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>